# Site settings
title: Midas van Oene
# email: midasvanoene@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Made with <a href='http://jekyllrb.com' target='_blank'>Jekyll</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://midasvo.nl" # the base hostname & protocol for your site
paginate: 5
github_username:  MidasVO
# bitbucket_username:  MidasVO
linkedin_username:  midasvanoene
# reddit_username:  midasvanoene
# trello_username: midasvo
permalink: /blog/:title
# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
analytics :
  provider : google
  google :
      tracking_id : 'UA-62348916-2'
